console.log("avanza");
console.log("elimina pila");
console.log("avanza");
console.log("elimina pila");
console.log("avanza");
console.log("elimina pila");
console.log("avanza");
console.log("elimina pila");
console.log("girar a la izquierda 90 grados");
console.log("avanza");
console.log("elimina pila");
console.log("avanza");
console.log("elimina pila");
console.log("avanza");
console.log("elimina pila");
console.log("avanza");
console.log("elimina pila");
console.log("avanza");
console.log("elimina pila");
console.log("LOGRADO");
